POST http://127.0.0.1:8000/api/devices/
Content-Type: application/json

{
  "name": "New Sensior",
  "location_id" : 7
}

###

POST http://127.0.0.1:8000/api/devices/co2-sensor/set-location/
Content-Type: application/json

{
  "location_id" : 2
}
